use std::{fs,path::{Path,PathBuf},process::Command};
use serde::{Deserialize,Serialize};
use zip::ZipArchive;
#[derive(Debug,Serialize,Deserialize,Clone)]pub struct Instance{pub id:String,pub name:String,pub version:String,pub loader:String,pub game_dir:String,pub max_memory:u32}
fn data_dir()->PathBuf{dirs::data_dir().unwrap_or_else(||PathBuf::from(".")).join("SM Launcher")}
#[tauri::command]pub fn list_instances()->Result<Vec<Instance>,String>{let f=data_dir().join("instances.json");if !f.exists(){return Ok(vec![])}serde_json::from_str(&fs::read_to_string(f).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
#[tauri::command]pub fn save_instances(mut instances:Vec<Instance>)->Result<(),String>{let d=data_dir();fs::create_dir_all(&d).map_err(|e|e.to_string())?;for i in &mut instances{if i.game_dir.is_empty(){i.game_dir=d.join("instances").join(&i.id).to_string_lossy().into_owned();fs::create_dir_all(&i.game_dir).map_err(|e|e.to_string())?}}fs::write(d.join("instances.json"),serde_json::to_vec_pretty(&instances).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
#[tauri::command]pub fn detect_java()->Result<String,String>{let o=Command::new("java").arg("-version").output().map_err(|e|format!("Java was not found: {e}"))?;if o.status.success(){Ok("java".into())}else{Err("Java could not be executed".into())}}
#[tauri::command]pub fn launch_process(java:String,args:Vec<String>,cwd:String)->Result<(),String>{Command::new(java).args(args).current_dir(cwd).spawn().map(|_|()).map_err(|e|e.to_string())}
#[tauri::command]
pub fn launch_minecraft(version:String,game_dir:String,username:String,uuid:String,access_token:String,max_memory:u32)->Result<(),String>{let root=PathBuf::from(&game_dir);let vd=root.join("versions").join(&version);let meta:serde_json::Value=serde_json::from_slice(&fs::read(vd.join(format!("{version}.json"))).map_err(|_|"Minecraft is not installed for this instance".to_string())?).map_err(|e|e.to_string())?;let natives=vd.join("natives");fs::create_dir_all(&natives).map_err(|e|e.to_string())?;if let Some(libs)=meta["libraries"].as_array(){for lib in libs{if !allowed(lib){continue}if let Some(n)=lib["downloads"]["classifiers"]["natives-windows"].as_object(){let p=n["path"].as_str().unwrap_or("");if !p.is_empty(){extract_native(&root.join("libraries").join(p),&natives)?}}}}let mut cp=Vec::new();if let Some(libs)=meta["libraries"].as_array(){for lib in libs{if !allowed(lib){continue}if let Some(p)=lib["downloads"]["artifact"]["path"].as_str(){cp.push(root.join("libraries").join(p).to_string_lossy().into_owned())}}}cp.push(vd.join(format!("{version}.jar")).to_string_lossy().into_owned());let asset_index=meta["assetIndex"]["id"].as_str().unwrap_or(&version).to_string();let token=if access_token.is_empty(){"0".to_string()}else{access_token};let mut args=vec![format!("-Xmx{}M",max_memory.max(1024)),format!("-Djava.library.path={}",natives.to_string_lossy()),"-cp".into(),cp.join(";")];args.push(meta["mainClass"].as_str().ok_or("Minecraft main class is missing")?.into());for(k,v)in[("--username",username),("--version",version.clone()),("--gameDir",game_dir.clone()),("--assetsDir",root.join("assets").to_string_lossy().into_owned()),("--assetIndex",asset_index),("--uuid",if uuid.is_empty(){"00000000-0000-0000-0000-000000000000".into()}else{uuid}),("--accessToken",token),("--userType","legacy".into()),("--versionType","release".into())]{args.push(k.into());args.push(v)}Command::new("java").args(args).current_dir(&root).spawn().map(|_|()).map_err(|e|format!("Could not start Minecraft: {e}"))}
fn allowed(x:&serde_json::Value)->bool{if let Some(r)=x.get("rules").and_then(|x|x.as_array()){let mut a=false;for z in r{if z["action"]=="allow"{a=true}if z["action"]=="disallow"&&z.get("os").and_then(|o|o.get("name")).and_then(|n|n.as_str())==Some("windows"){return false}}a}else{true}}
fn extract_native(file:&Path,out:&Path)->Result<(),String>{let f=fs::File::open(file).map_err(|e|e.to_string())?;let mut z=ZipArchive::new(f).map_err(|e|e.to_string())?;for i in 0..z.len(){let mut e=z.by_index(i).map_err(|e|e.to_string())?;let n=e.name().replace('\\',"/");if n.ends_with('/')||n.starts_with("META-INF/"){continue}let name=Path::new(&n).file_name().ok_or("Invalid native entry")?;let mut o=fs::File::create(out.join(name)).map_err(|e|e.to_string())?;std::io::copy(&mut e,&mut o).map_err(|e|e.to_string())?;}Ok(())}
