import { useEffect, useMemo, useState } from 'react';

type Page = 'home' | 'instances' | 'mods' | 'accounts' | 'settings';
type Instance = { id:string; name:string; version:string; loader:string; icon:string; gameDir:string; maxMemory:number };
type Account = { id:string; kind:string; username:string; uuid:string };
type LoginKind = 'microsoft' | 'elyby' | 'offline';

declare global { interface Window { smLauncher:any } }
const icons=['grass','diamond','nether','ender','redstone','command','sword','pickaxe'];

export function App(){
 const [page,setPage]=useState<Page>('home');
 const [instances,setInstances]=useState<Instance[]>([]);
 const [accounts,setAccounts]=useState<Account[]>([]);
 const [active,setActive]=useState('');
 const [theme,setTheme]=useState<'dark'|'light'>('dark');
 const [modal,setModal]=useState(false);
 const [loginOpen,setLoginOpen]=useState(false);
 const [loginKind,setLoginKind]=useState<LoginKind>('microsoft');
 const [authCode,setAuthCode]=useState<any>(null);
 const [busy,setBusy]=useState(false);
 const [loginForm,setLoginForm]=useState({username:'',password:'',totp:''});
 const [form,setForm]=useState({name:'Survival',version:'1.21.8',loader:'vanilla',icon:'grass',maxMemory:4096});
 const activeAccount=useMemo(()=>accounts.find(a=>a.id===active)??accounts[0],[accounts,active]);

 const refresh=async()=>{setInstances(await window.smLauncher.instances.list());setAccounts(await window.smLauncher.accounts.list());};
 useEffect(()=>{refresh();const fn=(_e:any,code:any)=>setAuthCode(code);window.smLauncher?.onMicrosoftCode?.(fn);return()=>window.smLauncher?.onMicrosoftCode?.removeListener?.(fn)},[]);
 const launch=async(id:string)=>{try{await window.smLauncher.instances.launch(id)}catch(e:any){alert(e?.message??String(e))}};
 const create=async()=>{try{await window.smLauncher.instances.create(form);setModal(false);await refresh()}catch(e:any){alert(e?.message??String(e))}};
 const login=async()=>{
  setBusy(true);
  try{
   if(loginKind==='microsoft') await window.smLauncher.accounts.microsoft();
   if(loginKind==='offline') await window.smLauncher.accounts.offline(loginForm.username);
   if(loginKind==='elyby') await window.smLauncher.accounts.elyby({username:loginForm.username,password:loginForm.password,totp:loginForm.totp||undefined});
   setLoginOpen(false);setLoginForm({username:'',password:'',totp:''});await refresh();
  }catch(e:any){alert(e?.message??String(e))}finally{setBusy(false)}
 };
 const removeAccount=async(id:string,username:string)=>{if(!confirm(`Remove ${username} from SM Launcher?`))return;try{await window.smLauncher.accounts.remove(id);await refresh()}catch(e:any){alert(e?.message??String(e))}};
 const title=page==='home'?'Library':page==='instances'?'Instances':page==='mods'?'Mods & Modpacks':page==='accounts'?'Accounts':'Settings';
 return <div className={`app ${theme}`}>
  <aside className="sidebar"><div className="brand"><div className="brandMark">SC</div><div><b>SM Launcher</b><small>Minecraft Java</small></div></div><nav>{([['home','⌂','Library'],['instances','▦','Instances'],['mods','✦','Mods'],['accounts','◉','Accounts'],['settings','⚙','Settings']] as const).map(([id,ic,label])=><button className={page===id?'nav active':'nav'} onClick={()=>setPage(id)} key={id}><span>{ic}</span>{label}</button>)}</nav><div className="sidebarBottom"><span className="statusDot"/> Services online</div></aside>
  <main className="main"><header className="topbar"><div><span className="eyebrow">SM LAUNCHER</span><h1>{title}</h1></div><div className="topActions"><button className="iconBtn" onClick={refresh}>↻</button><div className="profilePill"><span className="avatar">{activeAccount?.username?.[0]?.toUpperCase()??'?'}</span>{activeAccount?.username??'No account'}</div></div></header>
  {page==='home'&&<><section className="hero"><div><span className="eyebrow">MINECRAFT JAVA EDITION</span><h2>Your worlds. Your instances. Your way.</h2><p>Launch vanilla or modded Minecraft from a clean, fast library with isolated profiles and deep customization.</p><div className="heroActions"><button className="primary" onClick={()=>setPage('instances')}>View instances →</button><button className="secondary" onClick={()=>setModal(true)}>+ New instance</button></div></div><div className="heroLogo">SC</div></section><section className="section"><div className="sectionTitle"><div><h3>Recently played</h3><p className="muted">Jump straight back into your worlds.</p></div><button className="textBtn" onClick={()=>setPage('instances')}>View all →</button></div><div className="instanceGrid">{instances.slice(0,4).map(i=><InstanceCard key={i.id} instance={i} onLaunch={()=>launch(i.id)}/>)}{!instances.length&&<Empty title="Your library is empty" text="Create your first Minecraft instance." action={()=>setModal(true)}/>}</div></section><div className="cards3"><InfoCard icon="⚡" title="Fast & isolated" text="Every instance keeps its own files, settings and mods."/><InfoCard icon="🧩" title="Mod ready" text="Fabric, Forge, NeoForge and Quilt profiles."/><InfoCard icon="🎨" title="Customizable" text="Icons, memory, JVM arguments and themes."/></div></>}
  {page==='instances'&&<section className="section"><div className="sectionTitle"><div><h3>Your instances</h3><p className="muted">Manage separate Minecraft installations.</p></div><button className="primary" onClick={()=>setModal(true)}>+ New instance</button></div><div className="instanceGrid">{instances.map(i=><InstanceCard key={i.id} instance={i} onLaunch={()=>launch(i.id)}/>)}{!instances.length&&<Empty title="No instances" text="Create an instance to get started." action={()=>setModal(true)}/>}</div></section>}
  {page==='mods'&&<section className="section"><div className="sectionTitle"><div><h3>Mods & modpacks</h3><p className="muted">Manage content per instance.</p></div><button className="secondary">Browse Modrinth</button></div><div className="modBanner"><div className="modIcon">✦</div><div><b>Mod management ready</b><p>Instance-aware mods, modpacks, shaders and resource packs are organized here.</p></div></div><div className="catalog"><div className="catalogCard"><b>Modrinth</b><span>Discover community content</span></div><div className="catalogCard"><b>CurseForge</b><span>Modpack ecosystem</span></div><div className="catalogCard"><b>Shaders</b><span>Instance-scoped graphics</span></div></div></section>}
  {page==='accounts'&&<section className="section"><div className="sectionTitle"><div><h3>Accounts</h3><p className="muted">Securely manage Microsoft, Ely.by and offline profiles.</p></div><button className="primary" onClick={()=>setLoginOpen(true)}>+ Add account</button></div><div className="accountList">{accounts.map(a=><div className={`accountRow ${activeAccount?.id===a.id?'selected':''}`} key={a.id} onClick={()=>{setActive(a.id);window.smLauncher.accounts.setActive(a.id)}}><div className="avatar large">{a.username[0].toUpperCase()}</div><div><b>{a.username}</b><span>{a.kind} · {a.uuid.slice(0,8)}…</span></div><button className="iconBtn" title="Remove account" onClick={e=>{e.stopPropagation();removeAccount(a.id,a.username)}}>×</button><span className="accountCheck">{activeAccount?.id===a.id?'✓':''}</span></div>)}{!accounts.length&&<Empty title="No accounts" text="Add Microsoft, Ely.by or an offline profile." action={()=>setLoginOpen(true)}/>}</div></section>}
  {page==='settings'&&<section className="section"><div className="settingsPanel"><div><b>Appearance</b><p>Switch between polished dark and light modes.</p></div><div className="segmented"><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}>Dark</button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}>Light</button></div></div><div className="settingsPanel"><div><b>Instance storage</b><p>Each profile uses an isolated game directory.</p></div><span className="badge">Isolated</span></div><div className="settingsPanel"><div><b>Launcher engine</b><p>Minecraft Launcher Core with official game resources.</p></div><span className="badge">SM Core</span></div></section>}
  </main>
  {modal&&<div className="modalBackdrop"><div className="modal"><div className="modalHead"><div><span className="eyebrow">NEW INSTANCE</span><h3>Create instance</h3></div><button className="iconBtn" onClick={()=>setModal(false)}>×</button></div><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Minecraft version<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label>Loader<select value={form.loader} onChange={e=>setForm({...form,loader:e.target.value})}><option value="vanilla">Vanilla</option><option value="fabric">Fabric</option><option value="forge">Forge</option><option value="neoforge">NeoForge</option><option value="quilt">Quilt</option></select></label><label>Icon<div className="iconPicker">{icons.map(x=><button className={form.icon===x?'picked':''} onClick={()=>setForm({...form,icon:x})} key={x}>{x[0].toUpperCase()}</button>)}</div></label><label>Maximum RAM<input type="number" value={form.maxMemory} onChange={e=>setForm({...form,maxMemory:Number(e.target.value)})}/></label><div className="modalFoot"><button className="secondary" onClick={()=>setModal(false)}>Cancel</button><button className="primary" onClick={create}>Create instance</button></div></div></div>}
  {loginOpen&&<div className="modalBackdrop"><div className="modal"><div className="modalHead"><div><span className="eyebrow">ACCOUNT LOGIN</span><h3>Add Minecraft account</h3></div><button className="iconBtn" onClick={()=>setLoginOpen(false)}>×</button></div><div className="segmented"><button className={loginKind==='microsoft'?'selected':''} onClick={()=>setLoginKind('microsoft')}>Microsoft</button><button className={loginKind==='elyby'?'selected':''} onClick={()=>setLoginKind('elyby')}>Ely.by</button><button className={loginKind==='offline'?'selected':''} onClick={()=>setLoginKind('offline')}>Offline</button></div>{loginKind==='microsoft'&&<p className="muted">A secure Microsoft device-code sign-in will open. No Microsoft password is entered into SM Launcher.</p>}{loginKind!=='microsoft'&&<><label>Username / email<input value={loginForm.username} onChange={e=>setLoginForm({...loginForm,username:e.target.value})} placeholder={loginKind==='offline'?'PlayerName':'Email or username'}/></label>{loginKind==='elyby'&&<><label>Password<input type="password" value={loginForm.password} onChange={e=>setLoginForm({...loginForm,password:e.target.value})}/></label><label>2FA code <span className="muted">(optional)</span><input value={loginForm.totp} onChange={e=>setLoginForm({...loginForm,totp:e.target.value})} inputMode="numeric" maxLength={6}/></label></>}</>}<div className="modalFoot"><button className="secondary" onClick={()=>setLoginOpen(false)}>Cancel</button><button className="primary" disabled={busy} onClick={login}>{busy?'Signing in…':loginKind==='microsoft'?'Sign in with Microsoft':`Sign in ${loginKind==='elyby'?'to Ely.by':'offline'}`}</button></div></div></div>}
  {authCode&&<div className="toast"><b>Microsoft sign-in</b><span>{authCode.message??'Open the displayed link and enter the code.'}</span>{authCode.verification_uri&&<button className="secondary" onClick={()=>window.smLauncher.openExternal(authCode.verification_uri)}>Open</button>}<button onClick={()=>setAuthCode(null)}>×</button></div>}
 </div>
}
function InstanceCard({instance,onLaunch}:{instance:Instance;onLaunch:()=>void}){return <article className="instanceCard"><div className="instanceIcon">{instance.icon[0].toUpperCase()}</div><div className="instanceMeta"><b>{instance.name}</b><span>{instance.loader} · {instance.version}</span></div><button className="play" onClick={onLaunch}>▶</button><div className="cardBottom"><span>{instance.maxMemory} MB RAM</span><span>⋮</span></div></article>}
function InfoCard({icon,title,text}:{icon:string;title:string;text:string}){return <div className="infoCard"><span className="infoIcon">{icon}</span><div><b>{title}</b><p>{text}</p></div></div>}
function Empty({title,text,action}:{title:string;text:string;action:()=>void}){return <div className="empty"><div>▦</div><b>{title}</b><p>{text}</p><button className="secondary" onClick={action}>Create one</button></div>}
