import { useState } from 'react';

type Instance={id:string;name:string;loader:string;version:string};
export function ModsPage({instances}:{instances:Instance[]}){
 const [query,setQuery]=useState(''); const [results,setResults]=useState<any[]>([]); const [selected,setSelected]=useState(instances[0]?.id??''); const [busy,setBusy]=useState(false);
 const search=async()=>{if(!query.trim())return;setBusy(true);try{const data=await window.smLauncher.mods.search(query,instances.find(i=>i.id===selected)?.loader,instances.find(i=>i.id===selected)?.version);setResults(data.hits??[]);}catch(e:any){alert(e?.message??String(e));}finally{setBusy(false);}};
 const install=async(projectId:string)=>{if(!selected){alert('Create/select an instance first.');return;}setBusy(true);try{const versions=await fetch(`https://api.modrinth.com/v2/project/${projectId}/version`).then(r=>r.json());const compatible=versions.find((v:any)=>v.game_versions?.includes(instances.find(i=>i.id===selected)?.version)&&v.loaders?.includes(instances.find(i=>i.id===selected)?.loader));const version=compatible??versions[0];if(!version)throw new Error('No compatible mod version found.');await window.smLauncher.mods.install(selected,version.id);alert('Installed successfully.');}catch(e:any){alert(e?.message??String(e));}finally{setBusy(false);}};
 return <section className="section"><div className="sectionTitle"><div><h3>Mods & modpacks</h3><p className="muted">Search Modrinth and install directly into an instance.</p></div><div style={{display:'flex',gap:8}}><select value={selected} onChange={e=>setSelected(e.target.value)} className="modSelect"><option value="">Select instance</option>{instances.map(i=><option key={i.id} value={i.id}>{i.name} · {i.version}</option>)}</select><button className="primary" onClick={search} disabled={busy}>{busy?'Searching…':'Search'}</button></div></div><div className="searchBar"><input placeholder="Search mods, e.g. sodium, lithium, minimap…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()}/></div><div className="modResults">{results.map(r=><article className="resultCard" key={r.project_id}><div className="resultIcon">{r.icon_url?<img src={r.icon_url}/>:r.title?.[0]}</div><div><b>{r.title}</b><p>{r.description}</p><small>{r.author} · {r.downloads?.toLocaleString?.()??r.downloads} downloads</small></div><button className="secondary" onClick={()=>install(r.project_id)}>Install</button></article>)}{results.length===0&&<div className="empty"><div>✦</div><b>Find your next mod</b><p>Search the public Modrinth catalog. Installation is scoped to the selected instance.</p></div>}</div></section>
}
