import { useState } from 'react';

type Instance={id:string;name:string;loader:string;version:string};
type Hit={project_id:string;title:string;description:string;author?:string;downloads?:number;icon_url?:string};

export function ModsPage({instances}:{instances:Instance[]}) {
 const [query,setQuery]=useState(''); const [results,setResults]=useState<Hit[]>([]); const [selected,setSelected]=useState(instances[0]?.id??''); const [busy,setBusy]=useState(false);
 const search=async()=>{if(!query.trim())return;setBusy(true);try{const r=await fetch(`https://api.modrinth.com/v2/search?query=${encodeURIComponent(query)}`);if(!r.ok)throw new Error(`Modrinth request failed (${r.status})`);const data=await r.json();setResults(data.hits??[]);}catch(e){alert(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const install=async(projectId:string)=>{if(!selected){alert('Create/select an instance first.');return;}alert(`Selected ${projectId} for instance ${selected}. Native installer integration is being wired into Tauri.`);};
 return <section className="section"><div className="sectionTitle"><div><h3>Mods & modpacks</h3><p className="muted">Search Modrinth and manage content per instance.</p></div><div style={{display:'flex',gap:8}}><select value={selected} onChange={e=>setSelected(e.target.value)} className="modSelect"><option value="">Select instance</option>{instances.map(i=><option key={i.id} value={i.id}>{i.name} · {i.version}</option>)}</select><button className="primary" onClick={search} disabled={busy}>{busy?'Searching…':'Search'}</button></div></div><div className="searchBar"><input placeholder="Search mods and modpacks…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()}/></div><div className="modResults">{results.map(r=><article className="resultCard" key={r.project_id}><div className="resultIcon">{r.icon_url?<img src={r.icon_url} alt=""/>:r.title?.[0]}</div><div><b>{r.title}</b><p>{r.description}</p><small>{r.author??'Modrinth'} · {(r.downloads??0).toLocaleString()} downloads</small></div><button className="secondary" onClick={()=>install(r.project_id)}>Install</button></article>)}{results.length===0&&<div className="empty"><div>✦</div><b>Find your next mod</b><p>Search the public Modrinth catalog.</p></div>}</div></section>;
}
